export const FUND_LIST_SUCC = 'search/fund_list_succ'
export const FUND_SORT_CHANGE = 'fund/fund_sort_change'
export const FUND_CURRENT_PAGE_CHANGE = 'found/fund_current_page_change'
export const FUND_PAGE_TOTAL_CHANGE = 'found/fund_page_total_change'
export const FUND_PROJECT_TOTAL_CHANGE = 'found/fund_project_total_change'
export const FUND_PROJECT_DETAIL_CHANGE = 'found/fund_project_detail_change'
