export const TIP_EXIST_CHANGE = 'search/tip_exist_change'
export const SEARCH_INPUT_CHANGE = 'search/search_input_change'
export const SHOW_NO_FIELD_TIPS_CHANGE = 'search/show_no_field_tips_change'

export const SEARCH_FIELD_CHANGE = 'search/search_field_change'
export const SEARCH_FIELD_START = 'search/search_field_start'
export const SEARCH_FIELD_SUCC = 'search/search_field_succ'
export const SEARCH_FIELD_ERROR = 'search/search_field_error'
export const ACTIVE_FIELD_CHANGE = 'search/active_field_change'
export const ACTIVE_TAB_BAR_CHANGE = 'search/active_tab_bar_change'
export const CURRENT_REPORT_CHANGE = 'search/current_report_change'

export const RESEARCH_TREND_START = 'search/research_trend_start'
export const RESEARCH_TREND_SUCC = 'search/research_trend_succ'
export const RESEARCH_TREND_ERROR = 'search/research_trend_error'
export const HIGH_AUTHOR_SUCC = 'search/high_author_succ'
export const HIGH_ORG_SUCC = 'search/high_org_succ'
export const PROJECT_TREND_SUCC = 'search/project_trend_succ'
